# liquid_clustering_demo.py
# Demonstrate Liquid Clustering setup, migration from Z-Order, and the data-skipping payoff.
# Pairs with Module 3 (Delta Lake) and Module 6 (Performance).

# %% [markdown]
# # Liquid Clustering on Delta — the 2026 default
#
# Replaces partitioning + ZORDER for most tables. Incremental, log-aware, supports up to 4
# clustering keys, and (with `CLUSTER BY AUTO`) Predictive Optimization picks the keys.

# %% Setup
from pyspark.sql import SparkSession
spark: SparkSession  # provided by Databricks Connect or notebook env

CATALOG = "demo"
SCHEMA  = "lc_examples"


# %% Pattern 1 — New table with explicit cluster keys
def create_with_lc():
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA}")
    spark.sql(f"""
    CREATE TABLE IF NOT EXISTS {CATALOG}.{SCHEMA}.claim_line (
      claim_line_sk    BIGINT GENERATED BY DEFAULT AS IDENTITY,
      claim_id         STRING,
      claim_line_id    STRING,
      member_id        STRING,
      payer_id         STRING,
      service_date     DATE,
      service_year     INT GENERATED ALWAYS AS (year(service_date)),
      procedure_code   STRING,
      diagnosis_code   STRING,
      billed_amount    DECIMAL(18,2),
      paid_amount      DECIMAL(18,2),
      ingestion_ts     TIMESTAMP,
      CONSTRAINT positive_paid CHECK (paid_amount >= 0)
    )
    CLUSTER BY (member_id, service_date)
    TBLPROPERTIES (
      'delta.enableDeletionVectors'         = 'true',
      'delta.enableChangeDataFeed'          = 'false',
      'delta.dataSkippingNumIndexedCols'    = '8',
      'delta.dataSkippingStatsColumns'      =
        'service_date,member_id,payer_id,procedure_code,paid_amount,claim_id'
    )
    """)


# %% Pattern 2 — Auto Liquid Clustering (let Predictive Optimization pick)
def create_with_lc_auto():
    spark.sql(f"""
    CREATE TABLE IF NOT EXISTS {CATALOG}.{SCHEMA}.claim_line_auto (
      -- same schema as above ...
      claim_id STRING,
      member_id STRING,
      service_date DATE,
      payer_id STRING,
      paid_amount DECIMAL(18,2)
    )
    CLUSTER BY AUTO
    TBLPROPERTIES (
      'delta.enableDeletionVectors' = 'true'
    )
    """)
    # PO observes query patterns and picks cluster keys autonomously.
    # Recommended for greenfield UC managed tables in 2026.


# %% Pattern 3 — Migrating an existing partitioned/ZORDER table to LC
def migrate_to_lc():
    """
    LC is incompatible with partitioning + ZORDER on the same table.
    To migrate:
    1. ALTER TABLE … CLUSTER BY (...)
    2. Subsequent OPTIMIZE incrementally clusters by new keys
    3. Existing partition directories continue to exist (LC respects them);
       to drop partitioning entirely, you must rewrite.
    """
    spark.sql(f"""
    ALTER TABLE {CATALOG}.{SCHEMA}.claim_line_legacy
    CLUSTER BY (member_id, service_date)
    """)
    # Run OPTIMIZE to incrementally cluster — touches only unclustered ZCubes
    spark.sql(f"OPTIMIZE {CATALOG}.{SCHEMA}.claim_line_legacy")


# %% Pattern 4 — Verify clustering is active
def verify_clustering():
    desc = spark.sql(f"DESCRIBE DETAIL {CATALOG}.{SCHEMA}.claim_line").collect()[0]
    print("Cluster columns:", desc["clusteringColumns"])
    print("Number of files:", desc["numFiles"])
    print("Size in bytes:", desc["sizeInBytes"])

    history = spark.sql(f"DESCRIBE HISTORY {CATALOG}.{SCHEMA}.claim_line").limit(5).collect()
    for row in history:
        print(f"v{row.version}: {row.operation} | metrics={row.operationMetrics}")


# %% Anti-patterns — DON'T do
def anti_patterns():
    """
    1. Z-ORDER on a Liquid-Clustered table — mutually exclusive
    2. Partitioning by high-cardinality (member_id) — use LC instead
    3. CLUSTER BY (col1, col2, col3, col4, col5) — LC supports up to 4 keys; > 4 is rejected
    4. Forgetting OPTIMIZE — LC clustering happens incrementally on OPTIMIZE
       (or via Predictive Optimization on UC managed tables)
    """
    pass


# %% Sanity-check run
if __name__ == "__main__":
    create_with_lc()
    verify_clustering()
